# Pacaur shortcuts
abbr yas 'yay -Suy'
abbr yar 'yay -Rns'
abbr yss 'yay -Ss'
abbr yql 'yay -Ql'

# Git shortcuts
abbr gs   'git status'
abbr gst  'git stash'
abbr gstp 'git stash pop'
abbr ga   'git add'
abbr gaf  'git add -f'
abbr gap  'git add -p'
abbr gc   'git commit --verbose'
abbr gco  'git checkout'
abbr gcop 'git checkout -p'
abbr gcb  'git checkout -b'
abbr gp   'git push'
abbr gpo  'git push origin (b)'
abbr gpb  'git push origin (b)' # Bad..
abbr gpu  'git pull --rebase --autostash --gpg-sign origin master'
abbr gb   'git branch'
abbr gbv  'git branch -v'
abbr gd   'git diff'
abbr gr   'git reset'
abbr grb  'git rebase'
abbr grbc 'git rebase --continue'
abbr grbo 'git rebase "@{u}"'
abbr gl   'git lg'
abbr glp  'git lg -p'
abbr gf   'git fetch'
abbr gfo  'git fetch origin'
abbr gdc  'git diff --cached'
abbr gsw  'git switch'
abbr gswc 'git switch -c'

abbr 64d 'base64 -d'
abbr 64e 'base64'
abbr 0xd 'xxd -r -p'
abbr 0xe 'xxd -p | tr -d "\n"'

abbr v   'vim'
abbr r   'reset'
abbr s   'source'
abbr ecn 'echo -n'
