# The default library root directory.
directory: ~/music

# The default library database file to use.
library: ~/.config/beets/library.db

# Community plugins.
pluginpath: ~/.config/beets/plugins

# Bultin plugins.
plugins: discogs embedart badfiles fuzzy fetchart lyrics lastgenre fromfilename cmus spotify zero inline replaygain chroma duplicates

item_fields:
  filename: |
      import os
      from beets.util import bytestring_path
      return bytestring_path(os.path.splitext(os.path.basename(path))[0])

# Paths configuration.
paths:
  default: $albumartist/$album%aunique{}/$track $artist - $title
  # singleton: $artist/$artist - $title
  singleton: %if{$artist,$artist/$artist - $title,$artist/$filename}
  comp: None

  # Soundtracks.
  albumtype:soundtrack: Soundtracks/$album/$track $title

chroma:
  auto: yes

replaygain:
  backend: gstreamer
  auto: yes 

fetchart:
  auto: yes

# Acoustid token for submitting fingerprints.
acoustid:
  apikey: nMX1A4YJUn

# How to handle imports.
import:
  copy: yes
  write: yes

# Lyrics implementation.
lyrics:
  sources: genius lyrics.com lyricwiki musixmatch

# Remove id3 fields.
zero:
    fields: month day comments
    comments: [EAC, LAME, from.+collection, 'ripped by']
    update_database: true
