#!/bin/sh

# Load Xresources for all X programs.
xrdb ~/.config/X/resources

# Load keyboard changes from .Xmodmap.
xmodmap ~/.config/X/modmap
setxkbmap -option caps:escape &

# Start urxvt daemon.
urxvtd -q -f -o

# Add support for keyboard mouse clicks.
xkbset m

# Remove bell
xset -b

# Automatically lock after 5 minutes.
xautolock -time 5 -locker /usr/bin/physlock &

# Automatically lock on lid close.
xss-lock -- /usr/bin/physlock &

# Start i3.
exec i3
