#!/bin/sh

# Fix touch-pad scrolling.
ibm_trackpad_id=$(xinput | grep 'TPPS' | cut -d"=" -f2 | cut -f1)
xinput set-prop $ibm_trackpad_id "Evdev Wheel Emulation" 1
xinput set-prop $ibm_trackpad_id "Evdev Wheel Emulation Button" 2
xinput set-prop $ibm_trackpad_id "Evdev Wheel Emulation Timeout" 200
xinput set-prop $ibm_trackpad_id "Evdev Wheel Emulation Axes" 7 6 5 4

trackpoint_id=$(xinput | grep 'TrackPoint' | cut -d"=" -f2 | cut -f1)
xinput set-prop $trackpoint_id 'libinput Accel Speed' 1.0

# Load Xresources for all X programs.
xrdb ~/.config/X/resources

# Load keyboard changes from .Xmodmap.
xmodmap ~/.config/X/modmap
setxkbmap -option caps:escape &

# Start urxvt daemon.
urxvtd -q -f -o

# Add support for keyboard mouse clicks.
xkbset m

# Remove bell
xset -b

# Automatically lock after 5 minutes.
xautolock -time 5 -locker /usr/bin/sflock &

# Automatically lock on lid close.
xss-lock -- /usr/bin/sflock &

# Start i3.
exec i3
